### ISSUE TITLE
Plugin dosen't work with components 

### ISSUE THREAD

**Issue by otikk** [oc-shopaholic/oc-good-news-plugin#10]
Hi, Im newbabes in October and I like this plugin but i have problem to show by components the article list and others part of output. What doing I badly?
by Otto

**Comment by kharanenka** [comment]
Hi!
What code do you use in template?

**Comment by otikk** [comment]
Hi,
im only trying like rainlab blog to show article list of items by adding components to the partial file "{% component 'ArticleList' %}" and nothing  show. Im didn't look into plugin code still Im learning.

**Comment by kharanenka** [comment]
Our components do not have templates. Please read [documentation](https://github.com/lovata/oc-good-news-plugin/wiki).
