### ISSUE TITLE
Ссылка на полный текст статьи

### ISSUE THREAD

**Issue by moimirid** [oc-shopaholic/oc-good-news-plugin#11]
Пробежался по вашим примерам в документации, но так и не понял как вывести ссылку на полный текст статьи , например, из заголовка в превью.

**Comment by kharanenka** [comment]
Hi!
For example:
You have article.htm page
```
title = "Article page"
url = "/news/:slug"

[ArticlePage]
slug = "{{ :slug }}"
slug_required = 1
```
You can render link on article page with using code:
```twig
 <a href="{{ 'news-page'|page({ slug: obArticle.slug }) }}">
      {{ obArticle.title }}
 </a>
```
