### ISSUE TITLE
Please add method list newest

### ISSUE THREAD

**Issue by ANZ504** [oc-shopaholic/oc-good-news-plugin#36]
Currently you can't filter by the newest post.
Please add that method.

published()
It applies a filter by publishing status and publish the date for the elements of a collection.

Thank you

**Comment by igor-tv** [comment]
Hello,

Try applying the `sort('publish|desc')` method on your collection.

**Comment by ANZ504** [comment]
What I want to achieve is to use the new status and put a start and end date of a new news.

And so manage to create a component in which to place the new news that are updated in the established arrows

![Captura de Pantalla 2022-08-14 a la(s) 07 43 25](https://user-images.githubusercontent.com/66383317/184539880-989907cf-91c0-4fb2-846d-738f4aaac3ea.png)

**Comment by igor-tv** [comment]
Perhaps I misunderstood you. But by design, only articles with the Published status should be included in the collection. There are other tools for sorting and grouping articles, and this is not an article status. But you can extend the plugin logic as you need.

**Comment by ANZ504** [comment]
So the start and stop dates do not have a clear functionality?

The last question :)

**Comment by igor-tv** [comment]
It works like this. If an article has a status of Published, it will only be added to the collection if the current date is within the start and stop date of the article's publication.

**Comment by ANZ504** [comment]
thx
