### ISSUE TITLE
Pagination slug

### ISSUE THREAD

**Issue by dathwa** [oc-shopaholic/oc-good-news-plugin#38]
Hello.
For pagination, in my template file I have...
```
url = "/blog/:page?"
layout = "default"
title = "Blog"
```
And my pagination links are rendered like `blog/1, blog/2`, etc. But the pages are not recognised.
I need to set the links like this: `blog/?page=1, blog/?page=2`, etc.
Seems to be here...
```
public function getPageFromRequest()
    {
        $iPage = (int) trim(Input::get('page'));
        //Check page value
        if ($iPage < 1) {
            $iPage = 1;
        }

        return $iPage;
    }
```
this works `$iPage = (int) trim($this->param('page'));`

Thank-you

**Comment by kharanenka** [comment]
Hi! If your theme has some logic:
```twig
{% set iPage = Pagination.getPageFromRequest() %}
```
then you can change this logic in your theme to:
```twig
{% set iPage = this.param.page %}
```

**Comment by dathwa** [comment]
That worked 👍
