### ISSUE TITLE
Get article title for page onEnd

### ISSUE THREAD

**Issue by dathwa** [oc-shopaholic/oc-good-news-plugin#39]
Hello.
In the Rainlab/Blog plugin we can do something like below to update the page title dynamically.
Is there an equivalent example for extracting this data for the current page article?
Thank-you

```
function onEnd()
{
  if (isset($this['post'])) {
    $this->page->title = $this->post->title;
    $this->page->description = $this->post->excerpt;
  }
  else {
    return $this->controller->run('/404');
  }
}
```

**Comment by kharanenka** [comment]
Hi! You can get current article object from ArticlePage component and fill data in onEnd method
```php
$obArticleItem = $this->ArticlePage->get();
$this->page->title = $obArticleItem->title;
$this->page->description = $obArticleItem->...;
```

**Comment by dathwa** [comment]
Excellent response. Thank-you.
> Hi! You can get current article object from ArticlePage component and fill data in onEnd method
> 
> ```
> $obArticleItem = $this->ArticlePage->get();
> $this->page->title = $obArticleItem->title;
> $this->page->description = $obArticleItem->...;
> ```
